name: 'dbt_academy_henrique'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_academy_henrique:
    marts:
      +tags: [marts]
      +materialized: table
      +schema: marts
    intermediate:
      +tags: [intermediate]
      +materialized: view
      +schema: intermediate
    staging:
      +tags: [staging]
      +materialized: view
      +schema: staging

seeds:
  dbt_academy_henrique:
    sap_adventure_works:
      +schema: sap_adw

vars:
  surrogate_key_treat_nulls_as_empty_strings: true #turn on legacy behaviour